#!/bin/sh
### BEGIN INIT INFO
# Provides:             linux_daemon
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6 
# Short-Description:    linux daemon
# Description:          linux daemon template $
### END INIT INFO

# Actions
case "$1" in
  start)
    lxd
    ;;
  stop)
    pkill linux_daemon
    ;;
  restart)
    pkill linux_daemon
    lxd
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac

exit 0
